CREATE TABLE `case_studies` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NOT NULL,
  `sqft` INT NOT NULL,
  `type` VARCHAR(100) NOT NULL,
  `location` VARCHAR(255) NOT NULL,
  `timescale` VARCHAR(100) NOT NULL,
  `scope` VARCHAR(255) NOT NULL,
  `images` TEXT NOT NULL, -- JSON array of image filenames
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4; 